packages:
  - apps/*
  - packages/*

catalog:
  '@iconify/json': ^2.2.498
  '@types/bytes': ^3.1.5
  '@vitejs/plugin-vue': ^6.0.7
  '@vue/test-utils': ^2.4.11
  '@vueuse/core': ^14.3.0
  bytes: ^3.1.2
  happy-dom: ^20.10.6
  hono: ^4.12.29
  naive-ui: ^2.44.1
  vite: ^8.1.4
  vitest: ^4.1.10
  vue: ^3.5.39
  vue-tsc: ^3.3.7
  zod: ^4.4.3

allowBuilds:
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@types/node@24.13.3'
