/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/system/configs': RouteRecordInfo<
      '/system/configs',
      '/system/configs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/departments': RouteRecordInfo<
      '/system/departments',
      '/system/departments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dictionaries': RouteRecordInfo<
      '/system/dictionaries',
      '/system/dictionaries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/resources': RouteRecordInfo<
      '/system/resources',
      '/system/resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/roles': RouteRecordInfo<
      '/system/roles',
      '/system/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/users': RouteRecordInfo<
      '/system/users',
      '/system/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/403': RouteRecordInfo<
      '/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/settings': RouteRecordInfo<
      '/account/settings',
      '/account/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/system/configs'
        | '/system/departments'
        | '/system/dictionaries'
        | '/system/resources'
        | '/system/roles'
        | '/system/users'
      views:
        | 'default'
    }
    'src/pages/index/system/configs.vue': {
      routes:
        | '/system/configs'
      views:
        | never
    }
    'src/pages/index/system/departments.vue': {
      routes:
        | '/system/departments'
      views:
        | never
    }
    'src/pages/index/system/dictionaries.vue': {
      routes:
        | '/system/dictionaries'
      views:
        | never
    }
    'src/pages/index/system/resources.vue': {
      routes:
        | '/system/resources'
      views:
        | never
    }
    'src/pages/index/system/roles.vue': {
      routes:
        | '/system/roles'
      views:
        | never
    }
    'src/pages/index/system/users.vue': {
      routes:
        | '/system/users'
      views:
        | never
    }
    'src/pages/403.vue': {
      routes:
        | '/403'
      views:
        | never
    }
    'src/pages/account/settings.vue': {
      routes:
        | '/account/settings'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
